WHITESPACE = _{ " " | "\t" | "\r" | "\n" }

char = { ASCII_ALPHANUMERIC | "." | "_" | "/" }
string_non_null = { char+ }

number = _{float | integer}
float = {("-"|"+")? ~ ASCII_DIGIT* ~ (".") ~ ASCII_DIGIT*}
integer = {
    ("-"|"+")? ~ 
    ASCII_DIGIT*}

// TODO: add calls
add      = { "+" }
subtract = { "-" }
multiply = { "*" }
divide   = { "/" }
power    = { "^" }
modulus  = { "%" }
operation = _{ add | subtract | multiply | divide | modulus | power }

expr = { term ~ (operation ~ term)* }
term = _{ "(" ~ expr ~ ")" | number }
array =  {"["~term~(","~term)*~"]"}

semicol = _{";"}
equal = _{"="}

let_allocate = {"let" ~ string_non_null}
variable = {string_non_null}
assignment = {(let_allocate | variable) ~ equal ~ expr}
//for now it is number, make it term later for string, bool etc.

function_call = {string_non_null ~ "(" ~ string_non_null ~ ")"}

//TODO if stmt, while, (for iterated maybe)
condition = {string_non_null}
//TODO add if else if else if else
if_stmt = {"if" ~ "("? ~ condition ~ ")"? ~ "{" ~ values* ~ "}" ~ "else"? ~ "{" ~ values* ~ "}" }
while_stmt = {"while" ~ "("? ~ condition ~ ")"? ~ "{" ~ values* ~ "}"}

//TODO add arrays etc. (list, object)

file = {
    SOI ~
    values* ~
    EOI
}

values = _{( assignment | let_allocate | function_call) ~ semicol}