[package]
name = "parser"
version = "0.1.0"
authors = ["Ozan Karaali <ozan.karaali@gmail.com>"]
edition = "2018"

[dependencies]
pest = "2.1.3"
pest_derive = "2.1.0"
lazy_static = "1.4.0"

[dependencies.common]
path = "../common"

[dependencies.engine]
path = "../engine"