[package]
name = "parser"
version = "0.1.0"
authors = ["Ozan Karaali <ozan.karaali@gmail.com>"]
build = "build.rs"

[dependencies]
lalrpop-util = "0.16.2"
regex = "0.2.0"

[build-dependencies]
lalrpop = "0.16.2"

[dependencies.common]
path = "../common"